name: 🌻 Spec Proposal
description: Propose a change to the OpenQASM specification
title: "[proposal]:"
labels: ["proposal"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      placeholder: |
        Describe the proposed specification change here.

  - type: textarea
    id: motivation
    attributes:
      label: "Motivation"
      placeholder: |
        Motivate the proposed change here.

  - type: textarea
    id: authors
    attributes:
      label: "Authors"
      placeholder: |
        A list with the names, and optionally the Github handles, of the
        people involved in the proposal.

  - type: textarea
    id: examples
    attributes:
      label: "Examples"
      placeholder: |
        ```text
        // One or more examples of how to use this proposal in an OpenQASM
        // program.
        ```